{application,chatter,
             [{description,"Web Chatter"},
              {vsn,"0.0.1"},
              {registered,[]},
              {modules,[chatter,chatter_app,chatter_sup,index_dtl,room_server,
                        web_server]},
              {applications,[kernel,stdlib,sasl]},
              {included_applications,[misultin,erlydtl,ejson]},
              {mod,{chatter_app,[]}},
              {env,[]}]}.
